"""
Django settings for myapps project.

Generated by 'django-admin startproject' using Django 1.11.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^$-%yj#%u)t8oj4*9w55+l^8qoat+ihk=lh#t7wv=%zb0y#61*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'umarianaframeworks@gmail.com'
EMAIL_HOST_PASSWORD = 'ingsis601'
EMAIL_PORT = "587"
EMAIL_USE_TLS = True





# Application definition

INSTALLED_APPS = [
   
    'django.contrib.admin',
    'registration',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'social_django',
    'crispy_forms',
    'rest_framework',
    
    'album',
    
    'django_adminlte',
    'django_adminlte_theme',
   
    
 
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    
    'social_django.middleware.SocialAuthExceptionMiddleware',
    
]


ACCOUNT_ACTIVATION_DAYS = 7 
REGISTRATION_AUTO_LOGIN = True
SITE_ID = 1



LOGIN_REDIRECT_URL = '/album'
LOGIN_URL = 'login'
LOGOUT_URL = '/accounts/logout'


CRISPY_TEMPLATE_PACK = 'bootstrap4'

ROOT_URLCONF = 'myapps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            
                'social_django.context_processors.backends', 
                'social_django.context_processors.login_redirect',


            
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    
    'social_core.backends.twitter.TwitterOAuth',

    'social_core.backends.facebook.FacebookOAuth2',

    
    
    'social_core.backends.google.GoogleOAuth2',

    
    'django.contrib.auth.backends.ModelBackend',
   
)





WSGI_APPLICATION = 'myapps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'album',
        'USER': 'fernando',
        'PASSWORD': 'ferchos90',
        'HOST': 'localhost',
        'PORT': 5432,
        'CHARSET': 'UTF8',

    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
   {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'es-CO'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media/')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'media'),
)


#KEY TWITTER
SOCIAL_AUTH_TWITTER_KEY = 'hXOMpMLwNtpBaUpeBhEilBA1A'
SOCIAL_AUTH_TWITTER_SECRET = 'ZBNWyaoFliOmDaFal4BMh4rRFBC9BZEoZtt6CmN7YxoL5PKBEc'

#KEY FACEBOOK


SOCIAL_AUTH_FACEBOOK_KEY = '1761693887470347'
SOCIAL_AUTH_FACEBOOK_SECRET = 'bdf3bf00ba9fb4dc039ff8c264b173a3'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '498091193942-24torg7v9gcvr4td33p6o2851mf30h0r.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'hh7VSP4m3CUzesPPQTvctmBU'

