# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-21 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.BigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('celular', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('cantidad', models.BigIntegerField(blank=True, null=True)),
                ('precio', models.BigIntegerField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_venta', models.BigIntegerField(blank=True, null=True)),
                ('valor', models.BigIntegerField(blank=True, null=True)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Cliente')),
                ('productos', models.ManyToManyField(to='album.Producto')),
            ],
        ),
    ]
